blank_issues_enabled: false
contact_links:
  - name: Support & Troubleshooting with the Aleph Zero Community
    url: https://discord.gg/alephzero
    about: |
      For general problems with Aleph Zero, we encourage you to visit our discord server, where you are very likely to get your question answered by an Aleph Zero Team member or by a community member.